### ISSUE TITLE
Users (and guest users) can't write unless they are admin (root).

### ISSUE THREAD

**Issue by jtagcat** [Erriez/docker-samba#11]
At least when host's all perms are nobody:nobody, chown not allowed.

This was an issue on upstream, unsure if on the fork as well.

**Comment by Erriez** [comment]
Thanks for creating an issue. I was not able to reproduce this with tagged version `1.0.0` on Linux:

```bash
# Create share as normal user:
mkdir /tmp/share2
```

**docker-compose.yml**:
Create share with browsable, read/write, guest access permission:
```yaml
volumes:
      - /tmp/share1:/mnt:z
      - /tmp/share2:/share2:z
    # -s <name>; <path> [; browse; readonly; guest; users; admins; writelist; comment]
    command: '-s "Private share2;/share2;yes;no;yes" -p'
```

Files are read/writable via the Samba share. Can you reproduce this with `1.0.0`?
